# Generated by Django 2.1.1 on 2018-09-11 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mails', '0004_email_template'),
        ('members', '0009_auto_20180512_1810'),
        ('bookkeeping', '0015_auto_20180707_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.EMail')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('interval_start', models.DateTimeField(blank=True, null=True)),
                ('interval_end', models.DateTimeField()),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mails.MailTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='bookkeeping.ReminderGroup'),
        ),
    ]
