# Generated by Django 5.2.11 on 2026-09-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0017_auto_20200818_2002"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="import_identity",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="realtransactionsource",
            name="duplicate_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="realtransactionsource",
            name="imported_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="realtransactionsource",
            name="importer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="realtransactionsource",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
