# Generated by Django 5.2.11 on 2026-08-25 16:20

import byro.common.models.auditable
import byro.common.models.log
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0008_email_balance"),
        ("members", "0013_auto_20200820_2018"),
    ]

    operations = [
        migrations.CreateModel(
            name="PGPConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encryption_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Encrypt member emails with PGP"
                    ),
                ),
                (
                    "signing_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Sign outgoing emails with PGP"
                    ),
                ),
                (
                    "signing_key_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="Fingerprint of the organization's private key in the configured PGP backend.",
                        max_length=64,
                        verbose_name="Signing key fingerprint",
                    ),
                ),
                (
                    "keyserver_url",
                    models.TextField(
                        blank=True,
                        default="keys.openpgp.org\nkeyserver.ubuntu.com\npgp.mit.edu",
                        help_text="Enter one keyserver per line. They are tried in order.",
                        verbose_name="Keyserver URLs",
                    ),
                ),
                (
                    "missing_key_policy",
                    models.CharField(
                        choices=[("send_plain", "send_plain"), ("block", "block")],
                        default="send_plain",
                        max_length=10,
                        verbose_name="When no PGP key is available",
                    ),
                ),
                (
                    "invalid_key_policy",
                    models.CharField(
                        choices=[("send_plain", "send_plain"), ("block", "block")],
                        default="block",
                        max_length=10,
                        verbose_name="When a PGP key is invalid",
                    ),
                ),
                (
                    "unverified_key_policy",
                    models.CharField(
                        choices=[("send_plain", "send_plain"), ("block", "block")],
                        default="block",
                        max_length=10,
                        verbose_name="When a PGP key is unverified",
                    ),
                ),
                (
                    "expired_key_policy",
                    models.CharField(
                        choices=[("send_plain", "send_plain"), ("block", "block")],
                        default="block",
                        max_length=10,
                        verbose_name="When a PGP key is expired",
                    ),
                ),
                (
                    "refresh_keys_automatically",
                    models.BooleanField(
                        default=True, verbose_name="Refresh PGP keys automatically"
                    ),
                ),
                (
                    "key_refresh_interval_days",
                    models.PositiveIntegerField(
                        default=1,
                        verbose_name="Days between automatic PGP key refreshes",
                    ),
                ),
                (
                    "keyserver_timeout_seconds",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Keyserver timeout in seconds"
                    ),
                ),
                (
                    "send_expiry_reminders",
                    models.BooleanField(
                        default=True,
                        verbose_name="Remind members before PGP keys expire",
                    ),
                ),
                (
                    "expiry_reminder_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Days before expiry to send reminders"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(byro.common.models.log.LogTargetMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MemberPGPKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("public_key", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("application", "application"),
                            ("member_page", "member_page"),
                            ("manual_upload", "manual_upload"),
                            ("keyserver", "keyserver"),
                        ],
                        default="manual_upload",
                        max_length=13,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("valid", "valid"),
                            ("expired", "expired"),
                            ("revoked", "revoked"),
                            ("invalid", "invalid"),
                            ("not_found", "not_found"),
                            ("unverified", "unverified"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pgp_keys",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ("member", "-is_active", "fingerprint"),
                "unique_together": {("member", "fingerprint")},
            },
            bases=(
                byro.common.models.auditable.Auditable,
                models.Model,
                byro.common.models.log.LogTargetMixin,
            ),
        ),
    ]
