# Generated by Django 5.2.11 on 2026-09-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0009_pgpconfiguration_memberpgpkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="delivered_to",
            field=models.JSONField(
                blank=True, default=list, editable=False, verbose_name="Delivered to"
            ),
        ),
    ]
