# Generated by Django 5.2.11 on 2026-10-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0010_email_delivered_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="delivered_to_members",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                verbose_name="Delivered to members",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="to_type",
            field=models.CharField(
                choices=[
                    ("addr", "Specific address"),
                    ("member", "Member"),
                    ("all", "All members"),
                ],
                default="addr",
                max_length=6,
                verbose_name="Recipient type",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="to",
            field=models.CharField(
                blank=True,
                help_text="One email address or several addresses separated by commas.",
                max_length=1000,
                verbose_name="To",
            ),
        ),
    ]
