# Generated by Django 5.2.11 on 2026-10-02 12:27

from django.db import migrations

SPECIAL_ALL = "special:all"
SPECIAL_MEMBER_PREFIX = "special:member:"

ADDRESS = "addr"
MEMBER = "member"
ALL_MEMBERS = "all"


def migrate_special_recipients(apps, schema_editor):
    """Move the recipients that were encoded in ``to`` to ``to_type``.

    Only mails whose recipients are known without doubt are changed: by the
    primary key in ``special:member:<pk>``, or by the member that the balance
    reminder was explicitly created for. A plain address stays a plain
    address, it is never matched against the addresses of the members: several
    members may share one address.

    ``delivered_to_members`` is never filled here. The old data cannot prove
    which member a mail was delivered to: ``delivered_to`` only holds
    addresses, and ``members`` was also filled before sending (balance
    reminders) or by an address lookup. Unsent mails that carry a trace of an
    earlier delivery, or members that are not their recipient, are therefore
    left untouched. Sending them is refused until somebody reviews them.
    """
    EMail = apps.get_model("mails", "EMail")
    Member = apps.get_model("members", "Member")

    # Sent mails are never sent again, only their recipient type is recorded.
    EMail.objects.filter(to=SPECIAL_ALL, sent__isnull=False).update(
        to_type=ALL_MEMBERS, to=""
    )

    for mail in EMail.objects.filter(to=SPECIAL_ALL, sent__isnull=True):
        if mail.delivered_to or mail.members.exists():
            continue
        EMail.objects.filter(pk=mail.pk).update(to_type=ALL_MEMBERS, to="")

    # Sent mails never carry "special:member:": the old code replaced it with
    # the address of the member before sending.
    for mail in EMail.objects.filter(
        sent__isnull=True, to__startswith=SPECIAL_MEMBER_PREFIX
    ):
        try:
            member_pk = int(mail.to[len(SPECIAL_MEMBER_PREFIX) :])
        except ValueError:
            continue
        member = Member.objects.filter(pk=member_pk).first()
        if member is None or mail.delivered_to:
            continue
        if set(mail.members.values_list("pk", flat=True)) - {member.pk}:
            continue
        mail.members.add(member)
        EMail.objects.filter(pk=mail.pk).update(to_type=MEMBER, to="")

    # Balance reminders in the outbox: created with an explicit member, who is
    # also the member of the balance. They are left alone if somebody changed
    # the address in the draft.
    for mail in EMail.objects.filter(
        sent__isnull=True, balance__isnull=False, to_type=ADDRESS
    ).select_related("balance__member"):
        member = mail.balance.member
        if not mail.to or mail.to != member.email or mail.delivered_to:
            continue
        if set(mail.members.values_list("pk", flat=True)) != {member.pk}:
            continue
        EMail.objects.filter(pk=mail.pk).update(to_type=MEMBER, to="")


class NotReversibleError(Exception):
    """Mails exist that the schema before ``to_type`` cannot represent."""


def _legacy_to(mail):
    """Return the value ``to`` had for this mail before ``to_type`` existed.

    Raises ``ValueError`` with the reason if the old schema cannot express
    the recipients of the mail and what was delivered. The old schema knows
    recipients and deliveries by address only: it can address one member
    (``special:member:<pk>``) or all of them (``special:all``), and it skips
    every address in ``delivered_to`` when a mail is sent again.
    """
    if mail.to_type not in (MEMBER, ALL_MEMBERS):
        raise ValueError(f"its recipient type {mail.to_type!r} is unknown")

    if mail.sent is None:
        if mail.delivered_to or mail.delivered_to_members:
            # A retry by the old code would skip members by their address:
            # members sharing an address, or with a changed address, would be
            # skipped or mailed twice.
            raise ValueError(
                "it has been delivered to some of its members, which the old "
                "schema can only record by address"
            )
        if mail.to_type == ALL_MEMBERS:
            return SPECIAL_ALL
        member_pks = list(mail.members.order_by("pk").values_list("pk", flat=True))
        if len(member_pks) != 1:
            raise ValueError(
                f"it is addressed to {len(member_pks)} members, the old schema "
                "can only address exactly one member"
            )
        return f"{SPECIAL_MEMBER_PREFIX}{member_pks[0]}"

    # Sent mails are not sent again. The old code stored them with the
    # addresses they were sent to and kept their members as the history.
    if mail.to_type == ALL_MEMBERS:
        return SPECIAL_ALL
    unrecorded = [
        pk
        for pk in mail.members.order_by("pk").values_list("pk", flat=True)
        if str(pk) not in mail.delivered_to_members
    ]
    if unrecorded:
        # the address of today may not be the one the mail was sent to
        raise ValueError(
            "the address it was sent to is not recorded for the member(s) "
            + ", ".join(str(pk) for pk in unrecorded)
        )
    to = ", ".join(
        address
        for _pk, address in sorted(
            mail.delivered_to_members.items(), key=lambda item: int(item[0])
        )
    )
    if len(to) > 1000:
        raise ValueError("its addresses do not fit into the old field")
    return to


def restore_special_recipients(apps, schema_editor):
    """Write the recipients back to ``to``, for the code before ``to_type``.

    This is only done if every mail can be represented by the old schema
    without losing who it is addressed to or who received it. Otherwise
    nothing is changed and the migration is aborted: a mail that looked fine
    to the old code, but skipped a member or went to somebody twice, would be
    worse than a failed rollback. All mails are checked before the first one
    is written, and the migration runs in a transaction.

    Supported: mails to addresses (unchanged), unsent mails to all members or
    to exactly one member that have not been delivered to anybody, and sent
    mails. Not supported: unsent member mails without or with several
    members, partly delivered mails to members or to all members, and sent
    member mails without a recorded address.
    """
    EMail = apps.get_model("mails", "EMail")

    legacy_to = {}
    problems = []
    for mail in EMail.objects.exclude(to_type=ADDRESS).order_by("pk"):
        try:
            legacy_to[mail.pk] = _legacy_to(mail)
        except ValueError as reason:
            problems.append(f"mail {mail.pk}: {reason}")
    if problems:
        raise NotReversibleError(
            "The mail recipients cannot be migrated backwards, nothing has "
            "been changed. The schema before this migration cannot represent "
            f"{len(problems)} mail(s) without losing their member recipients "
            "or deliveries: "
            + "; ".join(problems[:20])
            + ("; ..." if len(problems) > 20 else "")
            + ". Send or discard these mails first, or restore a backup."
        )

    for pk, to in legacy_to.items():
        EMail.objects.filter(pk=pk).update(to=to)


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0011_email_recipient_type"),
        # the members and their balances are read here
        ("members", "0014_alter_member_options"),
    ]

    operations = [
        migrations.RunPython(migrate_special_recipients, restore_special_recipients),
    ]
