blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/byro/byro/discussions/categories/q-a
    about: Ask general questions and get help from the community in GitHub Discussions.
