# Generated by Django 5.2.12 on 2026-08-09 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0013_auto_20200820_2018"),
        ("public", "0004_auto_20200818_2002"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberChangeProposal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_id", models.CharField(max_length=200)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_proposals",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ("field_id",),
                "unique_together": {("member", "field_id")},
            },
        ),
    ]
