# Generated by Django 5.2.11 on 2026-09-03 23:17

import byro.common.models.log
import byro.mfa.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MFAConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "require_mfa",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, all users with access to the byro backend have to set up multi-factor authentication with an authenticator app (TOTP). Users without MFA are asked to set it up at their next login.",
                        verbose_name="Require MFA for all administrators",
                    ),
                ),
                (
                    "account_label",
                    models.CharField(
                        blank=True,
                        default="{association} - {username}",
                        help_text='Shown below "BYRO" in the authenticator app. Available placeholders: {username}, {email}, {name} (the user\'s name) and {association}. Colons are not allowed.',
                        max_length=128,
                        validators=[
                            byro.mfa.models.validate_account_label,
                            byro.mfa.models.validate_no_colon,
                        ],
                        verbose_name="Account name in authenticator apps",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(byro.common.models.log.LogTargetMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recovery code",
            },
        ),
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The human-readable name of this device.",
                        max_length=64,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=True, help_text="Is this device ready for use?"
                    ),
                ),
                (
                    "throttling_failure_timestamp",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="A timestamp of the last failed verification attempt. Null if last attempt succeeded.",
                        null=True,
                    ),
                ),
                (
                    "throttling_failure_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of successive failed attempts."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this device was initially created in the system.",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The most recent date and time this device was used.",
                        null=True,
                    ),
                ),
                ("encrypted_key", models.CharField(editable=False, max_length=255)),
                ("drift", models.SmallIntegerField(default=0)),
                ("last_t", models.BigIntegerField(default=-1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_totp_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TOTP device",
                "abstract": False,
            },
        ),
    ]
