# Generated by Django 5.2.11 on 2026-10-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mfa", "0002_mfa_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mfaconfiguration",
            name="policy",
            field=models.CharField(
                choices=[
                    ("optional", "Optional"),
                    ("required", "Required for all backend users"),
                    (
                        "required_except_oidc",
                        "Required for all backend users except OIDC logins",
                    ),
                ],
                default="optional",
                help_text="Choose whether MFA is optional, required for every backend login, or required except for sessions authenticated through OIDC. An authenticator that a user set up themselves is always required.",
                max_length=32,
                verbose_name="MFA policy",
            ),
        ),
    ]
