# Generated by Django 5.2.11 on 2026-10-04 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_auto_20181013_1611"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate, null=True),
        ),
    ]
