# Generated by Django 5.2.11 on 2026-10-01 19:43

from django.conf import settings
from django.db import migrations


def grant_existing_users_backend_access(apps, schema_editor):
    """Until now every account had unrestricted access to the whole backend.

    With ``is_staff`` and ``is_superuser`` being enforced from this release
    on, existing accounts keep exactly that access. The previous flag values
    are not stored, so this cannot be reversed.
    """
    User = apps.get_model(settings.AUTH_USER_MODEL)
    User.objects.update(is_staff=True, is_superuser=True)


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_alter_configuration_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            grant_existing_users_backend_access, migrations.RunPython.noop
        ),
    ]
