# Generated by Django 5.2.11 on 2026-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_grant_existing_users_backend_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="liability_interval",
            field=models.IntegerField(
                default=36,
                help_text="For which interval can you make members pay their outstanding fees?",
                verbose_name="Statute of limitations in months",
            ),
        ),
    ]
