# Generated by Django 5.2.11 on 2026-10-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_liability_interval_unit_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="currency",
            field=models.CharField(
                blank=True,
                default="EUR",
                help_text="E.g. EUR",
                max_length=3,
                null=True,
                verbose_name="Currency",
            ),
        ),
    ]
