# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("members", "0008_member_member_contact_type")]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_contact_type",
            field=models.CharField(
                choices=[
                    ("organization", "organization"),
                    ("person", "person"),
                    ("role", "role"),
                ],
                default="person",
                max_length=12,
                verbose_name="Contact type",
            ),
        )
    ]
