# Generated by Django 5.2.11 on 2026-09-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0013_auto_20200820_2018"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ("direct_address_name", "name")},
        ),
    ]
