#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import sys

# This file is execfile()d with the current directory set to its
# containing directory.

# -- General configuration ------------------------------------------------

sys.path.insert(0, os.path.abspath("../src"))

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "byro.settings")
django.setup()

# PyEnchant is required for spellchecking only, and somewhat bothersome
# to install on some systems.
try:
    import enchant

    HAS_PYENCHANT = True
except:
    HAS_PYENCHANT = False

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
]
if HAS_PYENCHANT:
    extensions.append("sphinxcontrib.spelling")

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of strings:
#
source_suffix = [".rst"]

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "byro"
copyright = "2017"
author = ""

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = ""
# The full version, including alpha/beta/rc tags.
release = ""

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_theme = "sphinx_rtd_theme"


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "byrodoc"


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "byro", "byro Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "byro",
        "byro Documentation",
        author,
        "byro",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# -- Options for internationalization -------------------------------------
locale_dirs = ["locale"]
gettext_compact = False

linkcheck_ignore = [
    r"http://localhost.*",
    "https://byro.yourdomain.com/",
    "https://github.com/byro/byro/issues/new",  # Redirects to login page
]

# Spelling options
if HAS_PYENCHANT:
    spelling_lang = "en_US"
    spelling_word_list_filename = "spelling_wordlist.txt"
    spelling_show_suggestions = True
