#!/usr/bin/env python3
"""Build the byro documentation with Zensical on Read the Docs.

Read the Docs runs this script from ``.readthedocs.yml`` (``build.jobs.build.html``).
It picks the language configuration from ``READTHEDOCS_LANGUAGE``, sets the
canonical site URL from ``READTHEDOCS_CANONICAL_URL`` and copies the result to
``$READTHEDOCS_OUTPUT/html/``, which is where Read the Docs expects the HTML.

Local simulation (from the repository root, Zensical installed):

    READTHEDOCS_LANGUAGE=de READTHEDOCS_OUTPUT=/tmp/rtd \\
    READTHEDOCS_CANONICAL_URL=https://byro.readthedocs.io/de/latest/ \\
    python docs/rtd_build.py

Without any environment variables it builds the English tree into
``docs/_build/rtd/`` and keeps the site URL from the configuration file.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LANGUAGES = ("de", "en")
DEFAULT_LANGUAGE = "en"


def language_from_environment() -> str:
    """Map the Read the Docs language code to one of our documentation trees."""
    raw = os.environ.get("READTHEDOCS_LANGUAGE", DEFAULT_LANGUAGE).strip().lower()
    code = raw.split("-")[0].split("_")[0] or DEFAULT_LANGUAGE
    if code not in LANGUAGES:
        sys.exit(
            f"Unsupported READTHEDOCS_LANGUAGE {raw!r}; "
            f"expected one of {', '.join(LANGUAGES)}"
        )
    return code


def derived_config(language: str, site_url: str | None, site_dir: Path) -> Path:
    """Write a copy of zensical.<lang>.toml with the given site URL and output directory.

    Zensical requires ``docs_dir`` to live below the directory of the configuration
    file, so the copy is written next to the originals as ``.zensical.rtd.toml``
    (ignored by git). Only whole top-level lines are replaced; the configuration
    files are kept simple enough for that on purpose.
    """
    source = REPO_ROOT / f"zensical.{language}.toml"
    text = source.read_text(encoding="utf-8")
    replacements = {
        "site_dir": f'site_dir = "{site_dir.relative_to(REPO_ROOT).as_posix()}"',
    }
    if site_url:
        replacements["site_url"] = f'site_url = "{site_url}"'
    for key, line in replacements.items():
        text, count = re.subn(rf"^{key} = .*$", line, text, count=1, flags=re.M)
        if count != 1:
            sys.exit(f"{source.name}: expected exactly one top-level '{key} =' line")
    target = REPO_ROOT / ".zensical.rtd.toml"
    target.write_text(
        f"# Generated by docs/rtd_build.py from {source.name}; do not edit.\n" + text,
        encoding="utf-8",
    )
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--output",
        help="directory that receives the HTML (default: $READTHEDOCS_OUTPUT/html "
        "or docs/_build/rtd)",
    )
    parser.add_argument(
        "--no-strict", action="store_true", help="do not abort on warnings"
    )
    args = parser.parse_args()

    language = language_from_environment()
    site_url = os.environ.get("READTHEDOCS_CANONICAL_URL", "").strip() or None
    if site_url and not site_url.endswith("/"):
        site_url += "/"

    if args.output:
        output = Path(args.output).resolve()
    elif os.environ.get("READTHEDOCS_OUTPUT"):
        output = Path(os.environ["READTHEDOCS_OUTPUT"]).resolve() / "html"
    else:
        output = REPO_ROOT / "docs" / "_build" / "rtd"

    site_dir = REPO_ROOT / ".cache" / "rtd" / language / "site"
    site_dir.parent.mkdir(parents=True, exist_ok=True)
    config = derived_config(language, site_url, site_dir)

    command = [sys.executable, "-m", "zensical", "build", "-f", str(config), "--clean"]
    if not args.no_strict:
        command.append("--strict")
    print(f"byro docs: language={language} site_url={site_url or '(from config)'}")
    print("byro docs:", " ".join(command))
    # Snippets (--8<--) resolve relative to the working directory: run from the root.
    result = subprocess.run(command, cwd=REPO_ROOT)
    if result.returncode != 0:
        return result.returncode

    if not (site_dir / "index.html").is_file():
        sys.exit(f"Zensical produced no index.html in {site_dir}")
    if output.exists():
        shutil.rmtree(output)
    shutil.copytree(site_dir, output)
    print(f"byro docs: copied {site_dir} -> {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
